name: Publish
on:
  push:
    branches:
      - main
  schedule:
  - cron:  '1 2,14 * * *'

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - run: |
          git clone --depth=1 https://github.com/misakaio/chnroutes2
          go run main.go
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: chnroutes2
